services:
  main-service:
    image: kopru-backend:latest
    container_name: voyager
    ports:
      - "127.0.0.1:8090:8090"
    environment:
      - PB_ORIGINS=https://admin.kopru.uz
    volumes:
      - pb_data:/pb_data
      - migrations:/migrations
    restart: always

volumes:
  pb_data:
  migrations:
