services:
  main-service:
    image: registry.digitalocean.com/edu-connect-docker-registry/edu-connect:35de4e6
    container_name: voyager
    ports:
      - "127.0.0.1:8090:8090"
    volumes:
      - pb_data:/pb_data
      - migrations:/migrations
    restart: always

volumes:
  pb_data:
  migrations:
