version: '3.8'

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-02-28T09-55-16Z-cpuv1
    #image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: miniusr
      MINIO_ROOT_PASSWORD: miniopass
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: always

volumes:
  minio_data:
