services:
  main-service:
    image: ${REGISTRY}/${IMAGE_NAME}:${SHORT_HASH}
    container_name: voyager
    ports:
      - "127.0.0.1:8090:8090"
    volumes:
      - pb_data:/pb_data
      - migrations:/migrations
    restart: always

volumes:
  pb_data:
  migrations:
