version: '3.8'

services:
  main-service:
    image: ${REGISTRY}/${IMAGE_NAME}:$(echo ${GITHUB_SHA} | head -c7)
    container_name: voyager
    ports:
      - "127.0.0.1:8090:8090"
    volumes:
      - pb_data:/pb_data
      - migrations:/migrations
    restart: always

volumes:
  pb_data:
  migrations:
