name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  REGISTRY: "registry.digitalocean.com/edu-connect-docker-registry"
  IMAGE_NAME: "edu-connect"
  
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600
    
    - name: Remove all old images
      run: if [ ! -z "$(doctl registry repository list | grep "$(echo $IMAGE_NAME)")" ]; then doctl registry repository delete-manifest $(echo $IMAGE_NAME) $(doctl registry repository list-tags $(echo $IMAGE_NAME) | grep -o "sha.*") --force; else echo "No repository"; fi

    - name: Push image to DigitalOcean Container Registry
      run: docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Deploy to DigitalOcean droplet via SSH action
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Create deployment directory if it doesn't exist
            mkdir -p /root/edu-connect

      - uses: actions/checkout@v4
      - name: Copy docker-compose files to the remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./docker-compose.yml,./docker-compose-minio.yml"
          target: ~/edu-connect/


      - name: Generate and Display .env File
        run: |
          SHORT_HASH=$(echo $GITHUB_SHA | head -c7)
          echo "IMAGE=${REGISTRY}/${IMAGE_NAME}:${SHORT_HASH}" > .env
          cat .env
      

      - name: Copy .env file to the remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ".env"
          target: ~/edu-connect/

        
      - name: Run the MinIO
        uses: hoverkraft-tech/compose-action@v2.0.2
        with:
          compose-file: "docker-compose-minio.yml"
          up-flags: "-d"

      - name: Authenticate with DOCR
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login registry.digitalocean.com -u "oauth2" -p "${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}"

      

      - name: Run the edu-connect app
        uses: hoverkraft-tech/compose-action@v2.0.2
        with:
          compose-file: "docker-compose.yml"
          up-flags: "-d"
