name: Docker Image CI

on:
  push:
    branches: [ "master" ]

  
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Copy files to the machine
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa" . kopru@${{ secrets.HOST }}://home/kopru/backend/

      - name: Build and run Docker container on DigitalOcean
        run: |
          ssh -i ~/.ssh/id_rsa kopru@${{ secrets.HOST }} << 'EOF'
            cd /home/kopru/backend
            docker build -t kopru-backend:latest .

            # Stop and remove the existing container if running
            docker compose -f docker-compose.yml down
            docker comopse -f docker-compose-minio.yml down

            # Run the containers
            docker compose -f docker-compose.yml up -d
            docker compose -f docker-compose-minio.yml up -d

            # Remove old images
            docker image prune -f
          EOF
